<<<<<<< HEAD
scoreboard objectives add uw:ry dummy
#start
execute @a[tag=uw:get_ry] ~ ~ ~ scoreboard players set @s uw:ry 0
execute @a[rym=0,ry=5,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 5
execute @a[rym=5,ry=10,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 10
execute @a[rym=10,ry=15,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 15
execute @a[rym=15,ry=20,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 20
execute @a[rym=20,ry=25,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 25
execute @a[rym=25,ry=30,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 30
execute @a[rym=30,ry=35,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 35
execute @a[rym=35,ry=40,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 40
execute @a[rym=40,ry=45,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 45
execute @a[rym=45,ry=50,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 50
execute @a[rym=50,ry=55,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 55
execute @a[rym=55,ry=60,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 60
execute @a[rym=60,ry=65,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 65
execute @a[rym=65,ry=70,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 70
execute @a[rym=70,ry=75,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 75
execute @a[rym=75,ry=80,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 80
execute @a[rym=80,ry=85,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 85
execute @a[rym=85,ry=90,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 90
execute @a[rym=90,ry=95,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 95
execute @a[rym=95,ry=100,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 100
execute @a[rym=100,ry=105,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 105
execute @a[rym=105,ry=110,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 110
execute @a[rym=110,ry=115,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 115
execute @a[rym=115,ry=120,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 120
execute @a[rym=120,ry=125,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 125
execute @a[rym=125,ry=130,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 130
execute @a[rym=130,ry=135,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 135
execute @a[rym=135,ry=140,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 140
execute @a[rym=140,ry=145,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 145
execute @a[rym=145,ry=150,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 150
execute @a[rym=150,ry=155,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 155
execute @a[rym=155,ry=160,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 160
execute @a[rym=160,ry=165,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 165
execute @a[rym=165,ry=170,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 170
execute @a[rym=170,ry=175,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 175
execute @a[rym=175,ry=180,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 180
execute @a[ry=-175,rym=-180,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 185
execute @a[ry=-170,rym=-175,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 190
execute @a[ry=-165,rym=-170,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 195
execute @a[ry=-160,rym=-165,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 200
execute @a[ry=-155,rym=-160,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 205
execute @a[ry=-150,rym=-155,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 210
execute @a[ry=-145,rym=-150,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 215
execute @a[ry=-140,rym=-145,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 220
execute @a[ry=-135,rym=-140,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 225
execute @a[ry=-130,rym=-135,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 230
execute @a[ry=-125,rym=-130,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 235
execute @a[ry=-120,rym=-125,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 240
execute @a[ry=-115,rym=-120,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 245
execute @a[ry=-110,rym=-115,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 250
execute @a[ry=-105,rym=-110,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 255
execute @a[ry=-100,rym=-105,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 260
execute @a[ry=-95,rym=-100,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 265
execute @a[ry=-90,rym=-95,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 270
execute @a[ry=-85,rym=-90,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 275
execute @a[ry=-80,rym=-95,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 280
execute @a[ry=-75,rym=-80,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 285
execute @a[ry=-70,rym=-75,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 290
execute @a[ry=-65,rym=-70,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 295
execute @a[ry=-60,rym=-65,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 300
execute @a[ry=-55,rym=-60,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 305
execute @a[ry=-50,rym=-55,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 310
execute @a[ry=-45,rym=-50,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 315
execute @a[ry=-40,rym=-45,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 320
execute @a[ry=-35,rym=-40,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 325
execute @a[ry=-30,rym=-35,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 330
execute @a[ry=-25,rym=-30,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 335
execute @a[ry=-20,rym=-25,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 340
execute @a[ry=-15,rym=-20,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 345
execute @a[ry=-10,rym=-15,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 350
execute @a[ry=-5,rym=-10,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 355
execute @a[ry=0,rym=-5,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 0
execute @a[tag=uw:get_ry] ~ ~ ~ tag @s remove uw:get_ry
=======
scoreboard objectives add uw:ry dummy
#start
execute @a[tag=uw:get_ry] ~ ~ ~ scoreboard players set @s uw:ry 0
execute @a[rym=0,ry=5,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 5
execute @a[rym=5,ry=10,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 10
execute @a[rym=10,ry=15,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 15
execute @a[rym=15,ry=20,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 20
execute @a[rym=20,ry=25,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 25
execute @a[rym=25,ry=30,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 30
execute @a[rym=30,ry=35,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 35
execute @a[rym=35,ry=40,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 40
execute @a[rym=40,ry=45,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 45
execute @a[rym=45,ry=50,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 50
execute @a[rym=50,ry=55,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 55
execute @a[rym=55,ry=60,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 60
execute @a[rym=60,ry=65,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 65
execute @a[rym=65,ry=70,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 70
execute @a[rym=70,ry=75,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 75
execute @a[rym=75,ry=80,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 80
execute @a[rym=80,ry=85,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 85
execute @a[rym=85,ry=90,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 90
execute @a[rym=90,ry=95,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 95
execute @a[rym=95,ry=100,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 100
execute @a[rym=100,ry=105,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 105
execute @a[rym=105,ry=110,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 110
execute @a[rym=110,ry=115,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 115
execute @a[rym=115,ry=120,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 120
execute @a[rym=120,ry=125,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 125
execute @a[rym=125,ry=130,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 130
execute @a[rym=130,ry=135,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 135
execute @a[rym=135,ry=140,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 140
execute @a[rym=140,ry=145,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 145
execute @a[rym=145,ry=150,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 150
execute @a[rym=150,ry=155,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 155
execute @a[rym=155,ry=160,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 160
execute @a[rym=160,ry=165,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 165
execute @a[rym=165,ry=170,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 170
execute @a[rym=170,ry=175,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 175
execute @a[rym=175,ry=180,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 180
execute @a[ry=-175,rym=-180,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 185
execute @a[ry=-170,rym=-175,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 190
execute @a[ry=-165,rym=-170,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 195
execute @a[ry=-160,rym=-165,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 200
execute @a[ry=-155,rym=-160,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 205
execute @a[ry=-150,rym=-155,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 210
execute @a[ry=-145,rym=-150,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 215
execute @a[ry=-140,rym=-145,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 220
execute @a[ry=-135,rym=-140,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 225
execute @a[ry=-130,rym=-135,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 230
execute @a[ry=-125,rym=-130,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 235
execute @a[ry=-120,rym=-125,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 240
execute @a[ry=-115,rym=-120,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 245
execute @a[ry=-110,rym=-115,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 250
execute @a[ry=-105,rym=-110,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 255
execute @a[ry=-100,rym=-105,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 260
execute @a[ry=-95,rym=-100,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 265
execute @a[ry=-90,rym=-95,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 270
execute @a[ry=-85,rym=-90,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 275
execute @a[ry=-80,rym=-95,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 280
execute @a[ry=-75,rym=-80,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 285
execute @a[ry=-70,rym=-75,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 290
execute @a[ry=-65,rym=-70,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 295
execute @a[ry=-60,rym=-65,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 300
execute @a[ry=-55,rym=-60,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 305
execute @a[ry=-50,rym=-55,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 310
execute @a[ry=-45,rym=-50,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 315
execute @a[ry=-40,rym=-45,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 320
execute @a[ry=-35,rym=-40,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 325
execute @a[ry=-30,rym=-35,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 330
execute @a[ry=-25,rym=-30,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 335
execute @a[ry=-20,rym=-25,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 340
execute @a[ry=-15,rym=-20,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 345
execute @a[ry=-10,rym=-15,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 350
execute @a[ry=-5,rym=-10,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 355
execute @a[ry=0,rym=-5,tag=uw:get_ry,scores={uw:ry=0}] ~ ~ ~ scoreboard players set @s uw:ry 0
execute @a[tag=uw:get_ry] ~ ~ ~ tag @s remove uw:get_ry
>>>>>>> d95f919c53aa8612409504198bbed77f930d5f64
#end