execute @a[scores={uw:actionbar=5..8,uw:number=0..21,uw:m2_number=0..62500}] ~ ~ ~ tag @s add "uw:actionbar/b_test_allow"
execute @a[scores={uw:actionbar=5},tag="uw:actionbar/b_test_allow"] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"Under World System\n您当前已创建 "},{"score":{"objective":"uw:number","name":"@s"}},{"text":"/21 个地皮\n已使用占地面积 "},{"score":{"objective":"uw:m2_number","name":"@s"}},{"text":"/62500m² (单位：1m=1方块)\n①开始创建  · 默认创建方法\n②开始创建 · 输入坐标创建方法\n③返回上一位置\n旋转水平视角切换选项\n扔出雪球确认选项"}]}
execute @a[scores={uw:actionbar=5},tag=!"uw:actionbar/b_test_allow"] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"Under World System\n您当前已创建 "},{"score":{"objective":"uw:number","name":"@s"}},{"text":"/21 个地皮\n已使用占地面积 "},{"score":{"objective":"uw:m2_number","name":"@s"}},{"text":"/62500m² (单位：1m=1方块)\nn①开始创建  · 默认创建方法\nn②开始创建 · 输入坐标创建方法\n③返回上一位置\n旋转水平视角切换选项\n扔出雪球确认选项"}]}
execute @a[scores={uw:actionbar=6},tag="uw:actionbar/b_test_allow"] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"Under World System\n您当前已创建 "},{"score":{"objective":"uw:number","name":"@s"}},{"text":"/21 个地皮\n已使用占地面积 "},{"score":{"objective":"uw:m2_number","name":"@s"}},{"text":"/62500m² (单位：1m=1方块)\n1.开始创建  · 默认创建方法\n②开始创建 · 输入坐标创建方法\n③返回上一位置\n旋转水平视角切换选项\n扔出雪球确认选项"}]}
execute @a[scores={uw:actionbar=6},tag=!"uw:actionbar/b_test_allow"] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"Under World System\n您当前已创建 "},{"score":{"objective":"uw:number","name":"@s"}},{"text":"/21 个地皮\n已使用占地面积 "},{"score":{"objective":"uw:m2_number","name":"@s"}},{"text":"/62500m² (单位：1m=1方块)\nn1.开始创建  · 默认创建方法\nn②开始创建 · 输入坐标创建方法\n③返回上一位置\n旋转水平视角切换选项\n扔出雪球确认选项"}]}
execute @a[scores={uw:actionbar=7},tag="uw:actionbar/b_test_allow"] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"Under World System\n您当前已创建 "},{"score":{"objective":"uw:number","name":"@s"}},{"text":"/21 个地皮\n已使用占地面积 "},{"score":{"objective":"uw:m2_number","name":"@s"}},{"text":"/62500m² (单位：1m=1方块)\n①开始创建  · 默认创建方法\n2.开始创建 · 输入坐标创建方法\n③返回上一位置\n旋转水平视角切换选项\n扔出雪球确认选项"}]}
execute @a[scores={uw:actionbar=7},tag=!"uw:actionbar/b_test_allow"] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"Under World System\n您当前已创建 "},{"score":{"objective":"uw:number","name":"@s"}},{"text":"/21 个地皮\n已使用占地面积 "},{"score":{"objective":"uw:m2_number","name":"@s"}},{"text":"/62500m² (单位：1m=1方块)\nn①开始创建  · 默认创建方法\nn2.开始创建 · 输入坐标创建方法\n③返回上一位置\n旋转水平视角切换选项\n扔出雪球确认选项"}]}
execute @a[scores={uw:actionbar=8},tag="uw:actionbar/b_test_allow"] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"Under World System\n您当前已创建 "},{"score":{"objective":"uw:number","name":"@s"}},{"text":"/21 个地皮\n已使用占地面积 "},{"score":{"objective":"uw:m2_number","name":"@s"}},{"text":"/62500m² (单位：1m=1方块)\nn①开始创建  · 默认创建方法\nn②开始创建 · 输入坐标创建方法\n3.返回上一位置\n旋转水平视角切换选项\n扔出雪球确认选项"}]}
execute @a[scores={uw:actionbar=8},tag=!"uw:actionbar/b_test_allow"] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"Under World System\n您当前已创建 "},{"score":{"objective":"uw:number","name":"@s"}},{"text":"/21 个地皮\n已使用占地面积 "},{"score":{"objective":"uw:m2_number","name":"@s"}},{"text":"/62500m² (单位：1m=1方块)\nn①开始创建  · 默认创建方法\nn②开始创建 · 输入坐标创建方法\n3.返回上一位置\n旋转水平视角切换选项\n扔出雪球确认选项"}]}
execute @a[tag="uw:actionbar/b_test_allow"] ~ ~ ~ tag @s remove "uw:actionbar/b_test_allow"
#b